-- MySQL Script generated by MySQL Workbench
-- Fri Sep 26 13:39:34 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema clubs_poucedor
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clubs_poucedor` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `clubs_poucedor` ;

-- -----------------------------------------------------
-- Table `clubs_poucedor`.`ecole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clubs_poucedor`.`ecole` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `sigle` VARCHAR(45) NULL,
  `autoriseInscription` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clubs_poucedor`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clubs_poucedor`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomBinome` VARCHAR(255) NULL,
  `estimation` VARCHAR(255) NULL,
  `commentaire` VARCHAR(255) NULL,
  `comment` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `ville` VARCHAR(255) NULL,
  `pays` VARCHAR(255) NULL,
  `yearOfCompetition` INT NULL,
  `distance` FLOAT NULL,
  `is_modified` INT NULL,
  `ecole_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_teams_ecole1_idx` (`ecole_id` ASC),
  CONSTRAINT `fk_teams_ecole1`
    FOREIGN KEY (`ecole_id`)
    REFERENCES `clubs_poucedor`.`ecole` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clubs_poucedor`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clubs_poucedor`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `sexe` VARCHAR(45) NULL,
  `promo` VARCHAR(45) NULL,
  `mail` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `create_time` VARCHAR(45) NULL,
  `update_time` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clubs_poucedor`.`personAndTeams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clubs_poucedor`.`personAndTeams` (
  `teams_id` INT NOT NULL,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`teams_id`, `person_id`),
  INDEX `fk_teams_has_person_person1_idx` (`person_id` ASC),
  INDEX `fk_teams_has_person_teams_idx` (`teams_id` ASC),
  CONSTRAINT `fk_teams_has_person_teams`
    FOREIGN KEY (`teams_id`)
    REFERENCES `clubs_poucedor`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teams_has_person_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `clubs_poucedor`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clubs_poucedor`.`actionRemarquable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clubs_poucedor`.`actionRemarquable` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `teams_id` INT NOT NULL,
  `pointsBonus` INT NULL,
  `nomAction` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `teams_id`),
  INDEX `fk_actionRemarquable_teams1_idx` (`teams_id` ASC),
  CONSTRAINT `fk_actionRemarquable_teams1`
    FOREIGN KEY (`teams_id`)
    REFERENCES `clubs_poucedor`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clubs_poucedor`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clubs_poucedor`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clubs_poucedor`.`ecole_has_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clubs_poucedor`.`ecole_has_admin` (
  `ecole_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`ecole_id`, `admin_id`),
  INDEX `fk_ecole_has_admin_admin1_idx` (`admin_id` ASC),
  INDEX `fk_ecole_has_admin_ecole1_idx` (`ecole_id` ASC),
  CONSTRAINT `fk_ecole_has_admin_ecole1`
    FOREIGN KEY (`ecole_id`)
    REFERENCES `clubs_poucedor`.`ecole` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ecole_has_admin_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `clubs_poucedor`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
